---
set_update_interval:
  target:
    entity:
      domain: weenect
  fields:
    update_interval:
      required: true
      example: "10M"
      default: "10M"
      selector:
        select:
          options:
            - "0S"
            - "30S"
            - "1M"
            - "2M"
            - "3M"
            - "5M"
            - "10M"

activate_super_live:
  target:
    entity:
      domain: weenect

refresh_location:
  target:
    entity:
      domain: weenect

ring:
  target:
    entity:
      domain: weenect

vibrate:
  target:
    entity:
      domain: weenect
