---
set_update_interval:
  target:
    entity:
      integration: weenect
    device:
      integration: weenect
  fields:
    update_interval:
      required: true
      example: "30M"
      default: "30M"
      selector:
        select:
          options:
            - "0S"
            - "30S"
            - "1M"
            - "5M"
            - "10M"
            - "30M"
            - "1H"

activate_super_live:
  target:
    entity:
      integration: weenect
    device:
      integration: weenect

refresh_location:
  target:
    entity:
      integration: weenect
    device:
      integration: weenect

ring:
  target:
    entity:
      integration: weenect
    device:
      integration: weenect

vibrate:
  target:
    entity:
      integration: weenect
    device:
      integration: weenect
